root: true
parser: babel-eslint
extends:
  - semistandard
  - plugin:prettier/recommended
rules:
  strict:
    - error
    - safe
  standard/computed-property-even-spacing: false
overrides:
  - files:
      - src/index.js
      - src/gnostic.js
      - .mocharc.js
    parserOptions:
      sourceType: script
  - files:
      - test/**/*.spec.js
    env:
      mocha: true
    globals:
      expect: false
      sinon: false
      rewiremock: false
